Starts from command line.

diff --git a/jdbld b/jdbld
--- a/jdbld
+++ b/jdbld
@@ -24,4 +24,9 @@ if [ ! -z "JAVA_HOME" ]; then
   javaCmd="$JAVA_HOME/bin/java"
 fi
 
+if [ ! -r "$jdbldDirectory/app/jdrupes-builder.jar" ]; then
+  echo >&2 "JDrupes Builder's executable jar not found."
+  exit 1
+fi
+
 $javaCmd -jar "$jdbldDirectory/app/jdrupes-builder.jar" "$@"
